/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistempeminjaman.view.user;

import com.toedter.calendar.JDateChooser;
import java.io.InputStream;
import java.sql.Blob;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import sistempeminjaman.controller.UserController;
import sistempeminjaman.db.Koneksi;
import sistempeminjaman.entity.UserDetail;
import sistempeminjaman.entity.Users;
import sistempeminjaman.model.UserModel;
import sistempeminjaman.view.FormDialog;

/**
 *
 * @author Nasrul
 */
public class FormRegistrasi extends FormDialog {

    public final static int AKSI_TAMBAH = 0;
    public final static int AKSI_EDIT = 1;
    
    private UserController uController;
    private Users user;
    
    private int inputMode = AKSI_TAMBAH;
    
    /**
     * Creates new form FormRegistrasi
     */
    public FormRegistrasi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buttonPinjam.setVisible(false);
    }
    
    public FormRegistrasi(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buttonPinjam.setVisible(false);
    }

    public JTextField getTeksNoId(){
        return teksNoId;
    }
    
    public JTextField getTeksNamaDepan(){
        return teksNamaDepan;
    }
    
    public JTextField getTeksNamaBelakang(){
        return teksNamaBelakang;
    }
    
    public JTextField getTeksEmail(){
        return teksEmail;
    }
    
    public JTextField getTeksNoTelp(){
        return teksNoTelp;
    }
    
    public JDateChooser getChooserTgl(){
        return tglChooser;
    }
    
    public JTextField getTeksAlamat(){
        return teksAlamat;
    }
    
    public void tampil(){
        uController = new UserController(this);
        pack();
        setLocationRelativeTo(super.getParent());
        setVisible(true);
    }
    
    public void tampil(UserController uController){
        setController(uController);
        uController.setDialogType(this);
        uController.isTransaksi();
        pack();
        setLocationRelativeTo(super.getParent());
        setVisible(true);
    }
    
    public void setButtonPinjam(boolean status){
        buttonPinjam.setVisible(status);
    }
    
    private void setController(UserController uController){
        this.uController = uController;
    }
    
    public void setAksi(int tipeAksi){
        setMode(tipeAksi);
    }
    
    public void setAksi(int tipeAksi, Users data){
        setMode(tipeAksi);
        setData(data);
        fill();
    }
    
    public void setData(Users data){
        this.user = data;
    }
    
//    private Blob setImage(){
//        uController.initGambar(user.getDetail().getIdUser());
//    }
    
    private void setMode(int mode){
        inputMode = mode;    
        if(inputMode == AKSI_EDIT){
            getTeksNoId().setEditable(false);
            buttonCetak.setEnabled(true);
        }else{
            getTeksNoId().setEditable(true);
            buttonCetak.setEnabled(false);
            
        }
    }
    
    private void fill(){
        getTeksNoId().setText(user.getNoId());
        getTeksAlamat().setText(user.getDetail().getAlamat());
        getTeksEmail().setText(user.getDetail().getEmail());
        getTeksNamaDepan().setText(user.getDetail().getNamaD());
        getTeksNamaBelakang().setText(user.getDetail().getNamaB());
        getTeksNoTelp().setText(user.getDetail().getTelp());
        getChooserTgl().setDate(user.getDetail().getTanggalLahir());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        teksNoId = new javax.swing.JTextField();
        teksNamaDepan = new javax.swing.JTextField();
        teksNamaBelakang = new javax.swing.JTextField();
        teksEmail = new javax.swing.JTextField();
        teksNoTelp = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tglChooser = new com.toedter.calendar.JDateChooser();
        teksAlamat = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        buttonBatal = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        buttonPinjam = new javax.swing.JButton();
        buttonCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("No ID : ");

        jLabel2.setText("Nama Depan : ");

        jLabel3.setText("Nama Belakang : ");

        jLabel4.setText("Email : ");

        jLabel5.setText("Telp : ");

        jLabel6.setText("Tanggal Lahir : ");

        jLabel7.setText("Alamat : ");

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(tglChooser, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(teksAlamat)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(teksNoTelp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teksEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teksNamaBelakang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teksNamaDepan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teksNoId, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(73, 73, 73)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(teksNoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(teksNamaDepan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(teksNamaBelakang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(teksEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(teksNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(teksAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonPinjam.setText("Pinjam");
        buttonPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPinjamActionPerformed(evt);
            }
        });

        buttonCetak.setText("Cetak");
        buttonCetak.setEnabled(false);
        buttonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPinjam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCetak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBatal)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBatal)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonPinjam)
                    .addComponent(buttonCetak))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        
        if(uController.validasi()){
            
            UserDetail userD = new UserDetail(getTeksNamaDepan().getText(), getTeksNamaBelakang().getText(), 
                    getTeksEmail().getText(), getTeksNoTelp().getText(), getTeksAlamat().getText(), getChooserTgl().getDate());
            userD.setNoId(getTeksNoId().getText());
            Users users = new Users();
            users.setNoId(getTeksNoId().getText());
            users.setuTipe("MEMBER");
            users.setsAktifasi("AKTIF");
            
            System.out.println("Cek : [namadepan/namabelakang/email/telp/alamat/tanggal] : " + userD.getIdUser()  + " / "  + userD.getNamaD() + " / " + userD.getNamaB() + " / " + userD.getEmail() + " / " + userD.getTelp()+ " / " + userD.getAlamat()+ " / " + userD.getTanggalLahir());
            
            uController.simpanUser(users, userD, inputMode);
            
        }
        
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void buttonPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPinjamActionPerformed
        // TODO add your handling code here:
        uController.setPilihBuku(user);
    }//GEN-LAST:event_buttonPinjamActionPerformed

    private void buttonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakActionPerformed
        // TODO add your handling code here:
        
        if(user == null) JOptionPane.showMessageDialog(this, "Error, kesalahan di Objek user");
        
        Map dataReport = new HashMap();
        dataReport.put("P_NOID", user.getNoId());
        
        InputStream dataSource = null;
        String dataDest = null;
        
        com.mysql.jdbc.Connection c = (com.mysql.jdbc.Connection) Koneksi.getConnection();
        
        try{

            dataSource = getClass().getResourceAsStream("/sistempeminjaman/laporan/kartu_anggota.jrxml");
            
            //System.out.println(System.getProperty("user.dir"));
            
            //dataDest = getClass().getResource("/org/sijadwal/laporan/laporanPerKelas.jasper").getFile();
            //dataSource = System.getProperty("user.dir") + "/src/org/sijadwal/laporan/laporanPerKelas.jrxml";
            //dataDest = System.getProperty("user.dir") + "/src/org/sijadwal/laporan/laporanPerKelas.jasper";
            
            //System.getenv(dataDest);
            
            JasperReport jasperReport = JasperCompileManager.compileReport(dataSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, dataReport, c);
            //JasperExportManager.exportReportToPdfStream(jasperPrint, null);
            //JasperExportManager.exportReportToHtmlFile(jasperPrint, dataDest);
            JasperViewer.viewReport(jasperPrint, false);
            
            uController.closeListUser();
            dispose();
            
        }catch(JRException ex){
            
            //JOptionPane.showMessageDialog(this, ex);
            
            JOptionPane.showMessageDialog(null, "Error : " + ex.getMessage());
            
            Logger.getLogger(FormRegistrasi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buttonCetakActionPerformed

    public void clear(){
        
        getTeksNoId().setText("");
        getTeksAlamat().setText("");
        getTeksEmail().setText("");
        getTeksNamaDepan().setText("");
        getTeksNamaBelakang().setText("");
        getTeksNoTelp().setText("");
        getChooserTgl().setDate(new Date());
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonCetak;
    private javax.swing.JButton buttonPinjam;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField teksAlamat;
    private javax.swing.JTextField teksEmail;
    private javax.swing.JTextField teksNamaBelakang;
    private javax.swing.JTextField teksNamaDepan;
    private javax.swing.JTextField teksNoId;
    private javax.swing.JTextField teksNoTelp;
    private com.toedter.calendar.JDateChooser tglChooser;
    // End of variables declaration//GEN-END:variables
}
