/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistempeminjaman.view.user;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sistempeminjaman.controller.BukuController;
import sistempeminjaman.controller.UserController;
import sistempeminjaman.entity.Buku;
import sistempeminjaman.entity.UserDetail;
import sistempeminjaman.entity.Users;
import sistempeminjaman.view.FormDialog;
import sistempeminjaman.view.buku.FormCariBuku;
import sistempeminjaman.view.buku.FormViewBuku;

/**
 *
 * @author Nasrul
 */
public class FormListUsers extends FormDialog {

    private UserController uController;
    private List<Users> list;
    
    /**
     * Creates new form FormListUsers
     */
    public FormListUsers(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    
    public FormListUsers(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    
    private void init(){
        uController = new UserController(this);
        
    }
    
    public void reload(){
        uController.loadInitLists();
    }
    
    public void tampil(){
        reload();
        pack();
        setLocationRelativeTo(super.getParent());
        setVisible(true);
    }
    
    public void tampil(UserController uController){
        setController(uController);
        uController.setDialogType(this);
        tampil();
    }
    
    private void setController(UserController uController){
        this.uController = uController;
    }
    
    private void setLabelInfo(String teksInfo){
        labelDesc.setText(teksInfo);
    }
    
    private void aktifRefresh(boolean status){
        buttonReset.setVisible(status);
    }
    
    public void setData(String teksInfo, List list, boolean rfButton){
        setList(list);
        setLabelInfo(teksInfo);
        aktifRefresh(rfButton);
        reloadTable();
    }
    
    private void setList(List<Users> list){
        this.list = list;
    }
    
    private void reloadTable(){
        // no_id, nama, email, telp, tanggal_lahir
        
        DateFormat df = new SimpleDateFormat("dd MMM YYYY");
        
        Object[][] listData = new Object[list.size()][6];
        int i = 0;
        for(Users user : list){
            listData[i][0] = i+1;
            listData[i][1] = user.getNoId();
            listData[i][2] = user.getDetail().getNamaD();
            listData[i][3] = user.getDetail().getEmail();
            listData[i][4] = user.getDetail().getTelp();
            listData[i][5] = df.format(user.getDetail().getTanggalLahir());
            i++;           
        }
        
        String[] columnNames = new String[]{
            "No", "No ID", "Nama", "Email", "Telp", "Tanggal Lahir"
        };
        
        tabelListUser.setModel(new DefaultTableModel(listData, columnNames));
        
        tabelListUser.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        int[] arrWidth = {40, 100, 100, 150, 100, 100};
        int x = 0;
        for(int w : arrWidth){
            tabelListUser.getColumnModel().getColumn(x).setPreferredWidth(w);
            x++;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelListUser = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        buttonKeluar = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        buttonCari = new javax.swing.JButton();
        labelDesc = new javax.swing.JLabel();
        buttonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tabelListUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelListUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelListUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelListUser);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });

        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonCari.setText("Cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        labelDesc.setText("Menampilkan total 5 Item");

        buttonReset.setText("X");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonKeluar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonKeluar)
                            .addComponent(buttonTambah)
                            .addComponent(buttonCari)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDesc)
                        .addComponent(buttonReset)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        FormRegistrasi frg = new FormRegistrasi(this, true);
        frg.setAksi(FormRegistrasi.AKSI_TAMBAH);
        frg.tampil(uController);
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void tabelListUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelListUserMouseClicked
        // TODO add your handling code here:
        int z = tabelListUser.getSelectedRow();
        
        if(z != -1){
            FormRegistrasi frg = new FormRegistrasi(this, true);
            frg.setAksi(FormRegistrasi.AKSI_EDIT, list.get(z));
            frg.tampil(uController);
        }
    }//GEN-LAST:event_tabelListUserMouseClicked

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        // TODO add your handling code here:
        FormCariUser formCariUser = new FormCariUser(this, true);
        formCariUser.tampil(uController);
    }//GEN-LAST:event_buttonCariActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        uController.loadInitLists();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonKeluarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDesc;
    private javax.swing.JTable tabelListUser;
    // End of variables declaration//GEN-END:variables
}
