/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistempeminjaman.view.peminjaman;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sistempeminjaman.controller.TransaksiController;
import sistempeminjaman.entity.Peminjaman;
import sistempeminjaman.view.FormDialog;

/**
 *
 * @author Nasrul
 */
public class FormListPeminjaman extends FormDialog {

    private TransaksiController tController;
    private List<Peminjaman> list;
    
    /**
     * Creates new form FormListUsers
     */
    public FormListPeminjaman(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tController = new TransaksiController(this);
    }
    
    public FormListPeminjaman(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tController = new TransaksiController(this);
    }
    
    private void init(){
        buttonReset.setVisible(false);
        if(tController.isPengembalian()){
            showFPencarian(true);
            tabelPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fAksiPengembalian(evt);
            }
        });
            
            
            
        }
        
    }
    
    private void showFPencarian(boolean st){
        buttonCari.setVisible(st);
    }
    
    private void fAksiPengembalian(java.awt.event.MouseEvent evt){
        int ff = tabelPeminjaman.getSelectedRow();
        if(ff != -1){
            tController.getDataPeminjaman(list.get(ff));
            dispose();
        }
        
    }
    
    public void reload(){
        showMessage("Pilih bulan dan tahun terlebih dahulu lalu tekan tampilkan");
    }
    
    public void tampil(){
        init();
        reload();
        pack();
        setLocationRelativeTo(super.getParent());
        setVisible(true);
    }
    
    public void tampil(TransaksiController tController){
        init();
        setController(tController);
        tController.setDialogType(this);
        tampil();
    }
    
    private void setController(TransaksiController tController){
        this.tController = tController;
    }
    
    
    public void setData(List list, boolean status){
        buttonReset.setVisible(status);
        setList(list);
        reloadTable();
    }
    
    private void setList(List<Peminjaman> list){
        this.list = list;
    }
    
    private void reloadTable(){
        // id_peminjaman, peminjam, judul, tanggal_pinjam, tanggal_kembali, sisa_hari, status
        
        DateFormat df = new SimpleDateFormat("dd MMM YYYY");
        
        Object[][] listData = new Object[list.size()][7];
        int i = 0;
        for(Peminjaman peminjaman : list){
            listData[i][0] = peminjaman.getStrIdPeminjaman();
            listData[i][1] = peminjaman.getMember().getUsername();
            listData[i][2] = peminjaman.getBuku().getJudul();
            listData[i][3] = df.format(peminjaman.getTanggal());
            listData[i][4] = df.format(peminjaman.getTanggalKembali());
            listData[i][5] = peminjaman.getMember().getIdUser();
            listData[i][6] = tController.statusPinjam(peminjaman.getStatus());
            i++;           
        }
        
        String[] columnNames = new String[]{
            "No Peminjaman", "Peminjam", "Judul Buku", "Tanggal Pinjam", "Tanggal Kembali", "Sisa Hari", "Status Peminjaman"
        };
        
        tabelPeminjaman.setModel(new DefaultTableModel(listData, columnNames));
        
        tabelPeminjaman.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        int[] arrWidth = {100, 130, 150, 120, 120, 40, 100};
        int x = 0;
        for(int w : arrWidth){
            tabelPeminjaman.getColumnModel().getColumn(x).setPreferredWidth(w);
            x++;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPeminjaman = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        buttonKeluar = new javax.swing.JButton();
        buttonCari = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbBulan = new javax.swing.JComboBox();
        cbTahun = new javax.swing.JComboBox();
        buttonTampilkan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tabelPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPeminjaman);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });

        buttonCari.setText("Cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        buttonReset.setText("X");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonKeluar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKeluar)
                    .addComponent(buttonCari)
                    .addComponent(buttonReset))
                .addContainerGap())
        );

        jLabel1.setText("mem-filter berdasarkan : ");

        cbBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        cbTahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013", "2014", "2015", "2016" }));

        buttonTampilkan.setText("Tampilkan");
        buttonTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTampilkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbBulan)
                        .addComponent(cbTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonTampilkan))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPeminjamanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelPeminjamanMouseClicked

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void buttonTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTampilkanActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Tahun : " + Integer.parseInt(cbTahun.getSelectedItem().toString()));
        System.out.println("Bulan : " + cbBulan.getSelectedIndex());
        tController.loadInitLists(cbBulan.getSelectedIndex(), Integer.parseInt(cbTahun.getSelectedItem().toString()));
        
    }//GEN-LAST:event_buttonTampilkanActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        // TODO add your handling code here:
        
        FormCariPeminjaman fcp = new FormCariPeminjaman(this, true);
        fcp.tampil(tController);
        
    }//GEN-LAST:event_buttonCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonTampilkan;
    private javax.swing.JComboBox cbBulan;
    private javax.swing.JComboBox cbTahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPeminjaman;
    // End of variables declaration//GEN-END:variables
}
