/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistempeminjaman.view;

import java.awt.Dimension;
import java.awt.Frame;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import sistempeminjaman.controller.KategoriController;
import sistempeminjaman.model.Session;
import sistempeminjaman.view.buku.FormListBuku;
import sistempeminjaman.view.buku.FormViewBuku;
import sistempeminjaman.view.kategori.FormListKategori;
import sistempeminjaman.view.kategori.FormViewKategori;
import sistempeminjaman.view.peminjaman.FormListPeminjaman;
import sistempeminjaman.view.peminjaman.FormPeminjaman;
import sistempeminjaman.view.pengembalian.FormPengembalian;
import sistempeminjaman.view.user.FormListUsers;
import sistempeminjaman.view.user.FormRegistrasi;

/**
 *
 * @author Nasrul
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        init();
    }
    
    private void init(){
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelInfoSess = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuGantiUser = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuLogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuTambahBuku = new javax.swing.JMenuItem();
        menuLihatBuku = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuTambahKategori = new javax.swing.JMenuItem();
        menuLihatKategori = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuRegistrasi = new javax.swing.JMenuItem();
        menuLihatUser = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuPinjaman = new javax.swing.JMenuItem();
        menuLihatPinjaman = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuPengembalian = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistempeminjaman/res/img/pb72.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jButton1.setPreferredSize(new java.awt.Dimension(75, 75));
        jButton1.setRolloverEnabled(false);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistempeminjaman/res/img/bk72.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jButton2.setPreferredSize(new java.awt.Dimension(75, 75));
        jButton2.setRolloverEnabled(false);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistempeminjaman/res/img/sgbk.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jButton3.setPreferredSize(new java.awt.Dimension(75, 75));
        jButton3.setRolloverEnabled(false);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>\nNasrul Aziz Gifari<br>\nDani Ramdani<br>\nHafid Nurdiansyah<br>\nM Yusuf\n</html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        labelInfoSess.setText("User [ Nasrul ] Login as [ Administrator ] on 21 Okt 2014 12:00:42");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInfoSess, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInfoSess)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SISTEM INFORMASI");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TAMAN BACAAN");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("\"YUK BACA\"");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Jl Bandung No 999 Bandung 40222");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Main");
        jMenu1.add(jSeparator1);

        menuGantiUser.setText("Ganti User");
        menuGantiUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGantiUserActionPerformed(evt);
            }
        });
        jMenu1.add(menuGantiUser);
        jMenu1.add(jSeparator6);

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master");

        menuTambahBuku.setText("Tambah Buku");
        menuTambahBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambahBukuActionPerformed(evt);
            }
        });
        jMenu2.add(menuTambahBuku);

        menuLihatBuku.setText("Lihat Buku");
        menuLihatBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLihatBukuActionPerformed(evt);
            }
        });
        jMenu2.add(menuLihatBuku);
        jMenu2.add(jSeparator5);

        menuTambahKategori.setText("Tambah Kategori");
        menuTambahKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambahKategoriActionPerformed(evt);
            }
        });
        jMenu2.add(menuTambahKategori);

        menuLihatKategori.setText("Lihat Kategori");
        menuLihatKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLihatKategoriActionPerformed(evt);
            }
        });
        jMenu2.add(menuLihatKategori);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        menuRegistrasi.setText("Registrasi");
        menuRegistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrasiActionPerformed(evt);
            }
        });
        jMenu3.add(menuRegistrasi);

        menuLihatUser.setText("Lihat User");
        menuLihatUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLihatUserActionPerformed(evt);
            }
        });
        jMenu3.add(menuLihatUser);
        jMenu3.add(jSeparator3);

        menuPinjaman.setText("Pinjaman");
        menuPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPinjamanActionPerformed(evt);
            }
        });
        jMenu3.add(menuPinjaman);

        menuLihatPinjaman.setText("Lihat Pinjaman");
        menuLihatPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLihatPinjamanActionPerformed(evt);
            }
        });
        jMenu3.add(menuLihatPinjaman);
        jMenu3.add(jSeparator4);

        menuPengembalian.setText("Pengembalian");
        menuPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPengembalianActionPerformed(evt);
            }
        });
        jMenu3.add(menuPengembalian);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLihatBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLihatBukuActionPerformed
        // TODO add your handling code here:
        
        tampilListBuku();
        
    }//GEN-LAST:event_menuLihatBukuActionPerformed

    private void menuTambahKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahKategoriActionPerformed
        // TODO add your handling code here:
        mnuTKategori();
    }//GEN-LAST:event_menuTambahKategoriActionPerformed

    private void menuLihatKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLihatKategoriActionPerformed
        // TODO add your handling code here:
        mnuLihatKategori();
    }//GEN-LAST:event_menuLihatKategoriActionPerformed

    private void menuRegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrasiActionPerformed
        // TODO add your handling code here:
        mnuRegistrasi();
    }//GEN-LAST:event_menuRegistrasiActionPerformed

    private void menuLihatUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLihatUserActionPerformed
        // TODO add your handling code here:
        mnuLihatUser();
    }//GEN-LAST:event_menuLihatUserActionPerformed

    private void menuTambahBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahBukuActionPerformed
        // TODO add your handling code here:
        mnuTambahBuku();
    }//GEN-LAST:event_menuTambahBukuActionPerformed

    private void menuPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPinjamanActionPerformed
        // TODO add your handling code here:
        mnuTPinjaman();
    }//GEN-LAST:event_menuPinjamanActionPerformed

    private void menuLihatPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLihatPinjamanActionPerformed
        // TODO add your handling code here:
        mnuListPeminjaman();
    }//GEN-LAST:event_menuLihatPinjamanActionPerformed

    private void menuPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPengembalianActionPerformed
        // TODO add your handling code here:
        mnuPengembalian();
    }//GEN-LAST:event_menuPengembalianActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuGantiUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGantiUserActionPerformed
        // TODO add your handling code here:

        FormLogin formLogin = new FormLogin(this, true);
        dispose();
        formLogin.tampil();

    }//GEN-LAST:event_menuGantiUserActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        menuLihatBukuActionPerformed(evt);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mnuTPinjaman();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mnuPengembalian();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mnuPengembalian(){
        FormPengembalian fpg = new FormPengembalian(this,true);
        fpg.tampil();
    }
    
    private void mnuListPeminjaman(){
        FormListPeminjaman flp = new FormListPeminjaman(this, true);
        flp.tampil();
    }
    
    private void mnuTPinjaman(){
        FormPeminjaman fpj = new FormPeminjaman(this, true);
        fpj.tampil();
    }
    
    private void mnuTambahBuku(){
        FormViewBuku fvb = new FormViewBuku(this, true);
        fvb.tampil();
    }
    
    private void mnuLihatUser(){
        FormListUsers flu = new FormListUsers(this, true);
        flu.tampil();
    }
    
    private void mnuRegistrasi(){
        FormRegistrasi frg = new FormRegistrasi(this, true);
        frg.tampil();
    }
    
    private void mnuLihatKategori(){
        FormListKategori flk = new FormListKategori(this, true);
        flk.tampil();
    }
    
    private void mnuTKategori(){
        FormViewKategori fvk = new FormViewKategori(this, true);
        fvk.tampil();
    }
    
    private void tampilListBuku(){
        FormListBuku formListBuku = new FormListBuku(this, true);
        formListBuku.tampil();
    }
    
    public void tampil(){
        
        getSess();
        setVisible(true);
        
    }
    
    private void getSess(){
        
        // User [ Nasrul ] Login as [ Administrator ] on 21 Okt 2014 12:00:42
        DateFormat df = new SimpleDateFormat("dd MMM yyyy hh:mm:ss");
        labelInfoSess.setText("User [ " + Session.getData().getUsername() + "] Login as [ " + Session.getData().getuTipe() + "] on " + df.format(new Date()));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelInfoSess;
    private javax.swing.JMenuItem menuGantiUser;
    private javax.swing.JMenuItem menuLihatBuku;
    private javax.swing.JMenuItem menuLihatKategori;
    private javax.swing.JMenuItem menuLihatPinjaman;
    private javax.swing.JMenuItem menuLihatUser;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuPengembalian;
    private javax.swing.JMenuItem menuPinjaman;
    private javax.swing.JMenuItem menuRegistrasi;
    private javax.swing.JMenuItem menuTambahBuku;
    private javax.swing.JMenuItem menuTambahKategori;
    // End of variables declaration//GEN-END:variables
}
