/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistempeminjaman.view.kategori;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import sistempeminjaman.controller.KategoriController;
import sistempeminjaman.entity.Kategori;
import sistempeminjaman.view.FormDialog;

/**
 *
 * @author Nasrul
 */
public class FormViewKategori extends FormDialog {

    public final static int AKSI_TAMBAH = 0;
    public final static int AKSI_EDIT = 1;
    
    private KategoriController kController;
    private Kategori kategori;
    
    private List<Kategori> listKategori;
    
    private int inputMode = AKSI_TAMBAH;
    
    /**
     * Creates new form FormViewKategori
     * @param parent
     * @param modal
     */
    public FormViewKategori(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    
    public FormViewKategori(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    public void tampil(){
        setController(new KategoriController(this));
        init();
        load();
    }
    
    public void load(){
        pack();
        setLocationRelativeTo(super.getParent());
        setVisible(true);
    }
    
    public void tampil(KategoriController kController){
        setController(kController);
        this.kController.setDialogType(this);
        init();
        if(inputMode == AKSI_EDIT) fill();
        load();
    }
    
    private void init(){
        kController.setKategoriParent();
    }
    
    public void reload(){
        init();
        clear();
    }
    
    public void setController(KategoriController kController){
        this.kController = kController;
    }
    
    public void setAksi(int tipeAksi){
        setMode(tipeAksi);
    }
    
    public void setAksi(int tipeAksi, Kategori data){
        setMode(tipeAksi);
        setData(data);
    }
    
    public void setData(Kategori data){
        this.kategori = data;
    }
    
    public void setKategori(List<Kategori> list){
        listKategori = list;
        changeCbKategori();
    }
    
    private void changeCbKategori(){
        
        getCbParent().removeAllItems();
        getCbParent().addItem("Tidak ada");
        for(Kategori kategoriParent : listKategori){
            getCbParent().addItem(kategoriParent.getNamaKategori());
        }
    }
    
    private void setMode(int mode){
        inputMode = mode;   
        if(mode == AKSI_TAMBAH){
            buttonHapus.setEnabled(false);
        }else{
            buttonHapus.setEnabled(true);
        }
    }
    
    private void fill(){
        getTeksKode().setText(String.valueOf(kategori.getIdKategori()));
        getTeksKategori().setText(kategori.getNamaKategori());
        getCbParent().setSelectedItem((kategori.getNamaParent() == null)?"Tidak ada":kategori.getNamaParent());
        
    }
    
    public JTextField getTeksKode(){
        return teksKode;
    }
    
    public JTextField getTeksKategori(){
        return teksKategori;
    }
    
    public JComboBox getCbParent(){
        return cbParent;
    }
    
    private void clear(){
        getTeksKode().setText("");
        getTeksKategori().setText("");
        getCbParent().setSelectedIndex(0);
        kategori = null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        teksKode = new javax.swing.JTextField();
        teksKategori = new javax.swing.JTextField();
        cbParent = new javax.swing.JComboBox();
        buttonBatal = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode : ");

        jLabel2.setText("Kategori : ");

        jLabel3.setText("Parent : ");

        teksKode.setText("AUTO");
        teksKode.setEnabled(false);

        cbParent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teksKategori)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(teksKode, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addComponent(cbParent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(teksKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(teksKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.setEnabled(false);
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBatal)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBatal)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonHapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        if(kController.validasi(this)){
            
            if(inputMode == AKSI_TAMBAH){
                kategori = new Kategori();
            }
            
            int ix = getCbParent().getSelectedIndex();
            
            //kategori.setIdKategori(Integer.parseInt(getTeksKode().getText()));
            kategori.setNamaKategori(getTeksKategori().getText());
            
            System.out.println("Nilai IX : " + ix);
            
            if(ix > 0){
                kategori.setpId(listKategori.get(ix).getIdKategori());
            }else{
                kategori.setpId(ix);
            }
            
            kController.simpanKategori(kategori, inputMode);
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        
        kController.hapus(getTeksKode().getText());
        
    }//GEN-LAST:event_buttonHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JComboBox cbParent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField teksKategori;
    private javax.swing.JTextField teksKode;
    // End of variables declaration//GEN-END:variables
}
