/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistempeminjaman.view.kategori;

import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sistempeminjaman.controller.KategoriController;
import sistempeminjaman.entity.Kategori;
import sistempeminjaman.view.FormDialog;

/**
 *
 * @author Nasrul
 */
public class FormListKategori extends FormDialog {

    private List<Kategori> list;
    private KategoriController kController;
    
    /**
     * Creates new form FormListKategori
     */
    public FormListKategori(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        kController = new KategoriController(this);
        init();
    }
    
    private void init(){
        
        kController.loadInitLists();
    }
    
    public void reload(){
        init();
        reloadTable();
    }
    
    public void tampil(){
        init();
        pack();
        setLocationRelativeTo(super.getParent());
        setVisible(true);
    }
    
    private void setLabelInfo(String teksInfo){
        labelDesc.setText(teksInfo);
    }
    
    public void setData(String teksInfo, List list){
        setList(list);
        setLabelInfo(teksInfo);
        reloadTable();
    }
    
    private void setList(List<Kategori> list){
        this.list = list;
    }
    
    private void reloadTable(){
        // no, ISBN, judul, penerbit, tahun terbit
        
        Object[][] listData = new Object[list.size()][2];
        int i = 0;
        for(Kategori kategori : list){
            listData[i][0] = i+1;
            listData[i][1] = kategori.getNamaKategori();
            i++;           
        }
        
        String[] columnNames = new String[]{
            "No", "Kategori"
        };
        
        tabelKategori.setModel(new DefaultTableModel(listData, columnNames));
        
        tabelKategori.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        int[] arrWidth = {40, 150};
        int x = 0;
        for(int w : arrWidth){
            tabelKategori.getColumnModel().getColumn(x).setPreferredWidth(w);
            x++;
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKategori = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        buttonKeluar = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        labelDesc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tabelKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKategori);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        buttonKeluar.setText("Keluar");

        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        labelDesc.setText("Menampilkan 5 Item");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addComponent(buttonTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonKeluar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        FormViewKategori fvk = new FormViewKategori(this, true);
        fvk.setAksi(FormViewKategori.AKSI_TAMBAH);
        fvk.tampil(kController);
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void tabelKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKategoriMouseClicked
        // TODO add your handling code here:
        
        int xx = tabelKategori.getSelectedRow();
        if(xx != -1){
            Kategori kategori = list.get(xx);
            //System.out.println("Terpilih : " + kategori.getIdKategori() + " - " + kategori.getNamaKategori() + " - " + kategori.getNamaParent());
            FormViewKategori fvk = new FormViewKategori(this, true);
            fvk.setAksi(FormViewKategori.AKSI_EDIT, kategori);
            fvk.tampil(kController);
        }
        
    }//GEN-LAST:event_tabelKategoriMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDesc;
    private javax.swing.JTable tabelKategori;
    // End of variables declaration//GEN-END:variables
}
